version: '3.9'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: dev-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev_db
    ports:
    - 5432:5432
    expose:
    - '5432'
    networks:
    - app-network

  test-postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
    - 5434:5432   # Use a different port to avoid conflicts with the main database
    expose:
    - '5434'   # Exposing the different port for clarity
    networks:
    - app-network

  backend:
    build: ./backend
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 80 --workers 1 --proxy-headers --reload"
    volumes:
    - ./backend:/usr/src/app
    tty: true
    env_file: .env
    depends_on:
    - postgres
    ports:
    - 3000:80
    networks:
    - app-network
    healthcheck:
      test: [CMD, curl, -f, http://localhost:3000/status]
      interval: 30s
      timeout: 10s
      retries: 5


networks:
  app-network:
