name: Main Workflow - Build Docker image and push to DockerHub
on:
  pull_request:
    types: closed
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push register app
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./backend
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/register:latest
